version: '2.1'
services:
  kafka:
    hostname: kafka
    container_name: kafka
    image: quay.io/strimzi/kafka:0.35.1-kafka-3.4.0
    command: [
      "sh", "-c",
      "./bin/kafka-storage.sh format -t RKNWDmq7T7CrvswcCYFCFg -c ./config/kraft/server.properties && bin/kafka-server-start.sh ./config/kraft/server.properties --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override num.partitions=$${KAFKA_NUM_PARTITIONS} --override group.min.session.timeout.ms=$${KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS}"
    ]
    ports:
      - 9092:9092
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 100
    networks:
      - demo-network
  connect:
    hostname: connect
    container_name: connect
    image: quay.io/strimzi/kafka:0.33.0-kafka-3.3.2
    command: [
      "sh", "-c",
      "bin/connect-distributed.sh config/connect-distributed.properties"
    ]
    volumes:
      - ./connect/config/connect-distributed.properties:/opt/kafka/config/connect-distributed.properties
      - ./connect/plugins/debezium-connector-mysql:/opt/connectors/debezium-connector-mysql
      - ./connect/plugins/mongodb-kafka-connect-mongodb:/opt/connectors/mongodb-kafka-connect-mongodb
    depends_on:
      - kafka
      - mysql
      - mongodb
    ports:
      - 8083:8083
    networks:
      - demo-network
  connectors:
    hostname: connectors
    container_name: connectors
    image: debezium/tooling:latest
    command: [
      "sh", "-c",
      "/home/register_connectors.sh"
    ]
    volumes:
      - ./connect/register_connectors.sh:/home/register_connectors.sh
      - ./connect/create_mongodb_sink_connector.json:/home/create_mongodb_sink_connector.json
      - ./connect/create_mysql_dbz_source_connector.json:/home/create_mysql_dbz_source_connector.json
    depends_on:
      - connect
      - mysql
      - mongodb
    networks:
      - demo-network
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    command: --default-authentication-plugin=mysql_native_password --log-bin=binlog --server-id=12345
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=debezium 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - demo-network
  mongodb:
    image: mongo:6.0.4
    hostname: mongodb
    container_name: mongodb
    restart: on-failure
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'show dbs' | mongosh admin --port 27017 --quiet | grep admin
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - demo-network
  eda-cep-generator:
    hostname: eda-cep-generator
    container_name: eda-cep-generator
    image: quay.io/rhdevelopers/eda-cep-data-generator:v23.02
    depends_on:
      - kafka
    networks:
      - demo-network
  eda-cep-enricher:
    hostname: eda-cep-enricher
    container_name: eda-cep-enricher
    image: quay.io/rhdevelopers/eda-cep-data-enricher:v23.02
    depends_on:
      - kafka
    networks:
      - demo-network
networks:
  demo-network:
    name: eda-cep-demo
