apiVersion: v1
kind: Service
metadata:
  name: eda-mtp-consumer
  labels:
    app: eda-mtp-consumer
spec:
  ports:
    - port: 8080
  selector:
    app: eda-mtp-consumer
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-mtp-consumer
  labels:
    app: eda-mtp-consumer
    app.kubernetes.io/part-of: message-translator-pattern
spec:
  selector:
    matchLabels:
      app: eda-mtp-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eda-mtp-consumer
    spec:
      containers:
      - image: quay.io/rhdevelopers/eda-mtp-consumer-app:v23.02
        name: eda-mtp-consumer
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"kafka"}]'
  name: topic-consumer
  labels:
    app: topic-consumer
    app.kubernetes.io/part-of: message-translator-pattern
spec:
  selector:
    matchLabels:
      app: topic-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: topic-consumer
    spec:
      containers:
      - name: topic-consumer
        image: quay.io/strimzi/kafka:0.35.1-kafka-3.4.0
        command: [
          "sh", "-c",
          "bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic pos-transactions --from-beginning"
        ]
