apiVersion: v1
kind: Service
metadata:
  name: eda-op-order-service
  labels:
    app: eda-op-order-service
spec:
  ports:
    - port: 8080
      name: eda-op-order-service
  selector:
    app: eda-op-order-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"mysql"}]'
  name: eda-op-order-service
  labels:
    app: eda-op-order-service
    app.kubernetes.io/part-of: outbox-pattern
    app.openshift.io/runtime: spring
spec:
  selector:
    matchLabels:
      app: eda-op-order-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eda-op-order-service
    spec:
      containers:
      - image: quay.io/rhdevelopers/eda-op-order-service:v23.09.03
        name: eda-op-order-service
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 3
          periodSeconds: 15
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"kafka"}]'
  name: outbox-consumer
  labels:
    app: outbox-consumer
    app.kubernetes.io/part-of: outbox-pattern
spec:
  selector:
    matchLabels:
      app: outbox-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: outbox-consumer
    spec:
      containers:
      - name: outbox-consumer
        image: quay.io/strimzi/kafka:0.35.1-kafka-3.4.0
        command: [
          "sh", "-c",
          "bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic mysql.outbox_demo.outbox_event --from-beginning"
        ]
