apiVersion: batch/v1
kind: Job
metadata:
  name: orders-creator
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"eda-op-order-service"}]'
  labels:
    app: orders-creator
    app.kubernetes.io/part-of: outbox-pattern
spec:
  template:
    spec:
      containers:
      - name: orders-creator
        image: quay.io/debezium/tooling:1.2
        command: [
          "bash","/home/create_orders.sh"
        ]
        volumeMounts:
            - name: orders-creator
              mountPath: /home
      restartPolicy: OnFailure
      volumes:
        - name: orders-creator
          configMap:
            name: orders-config
  backoffLimit: 10
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  labels:
    app: orders-creator
data:
  create_orders.sh: |
    #!/bin/bash
    echo "waiting order service to start listening..."
    while [ $(curl -s -o /dev/null -w %{http_code} http://eda-op-order-service:8080/actuator/health) -eq 000 ] ; do 
        echo -e $(date) " order service listener HTTP state: " $(curl -s -o /dev/null -w %{http_code} http://eda-op-order-service:8080/actuator/health) " (waiting for 200)"
        sleep 2
    done
    echo "order service is up!"
    sleep 5
    curl -X POST -H "Content-Type: application/json" -d @/home/order1.json http://eda-op-order-service:8080/api/orders
    sleep 1
    curl -X POST -H "Content-Type: application/json" -d @/home/order2.json http://eda-op-order-service:8080/api/orders
    sleep 1
    curl -X PUT -H "Content-Type: application/json" -d @/home/order1_update1.json http://eda-op-order-service:8080/api/orders/1/lines/1
    sleep 1
    curl -X PUT -H "Content-Type: application/json" -d @/home/order1_update2.json http://eda-op-order-service:8080/api/orders/1/lines/2
    sleep 1
    curl -X PUT -H "Content-Type: application/json" -d @/home/order2_update1.json http://eda-op-order-service:8080/api/orders/2/lines/3
    sleep 1
    curl -X PUT -H "Content-Type: application/json" -d @/home/order2_update2.json http://eda-op-order-service:8080/api/orders/2/lines/4
    sleep 1
    curl -X PUT -H "Content-Type: application/json" -d @/home/order2_update3.json http://eda-op-order-service:8080/api/orders/2/lines/5
    echo "DONE with creating/updating orders!"

  order1.json: |
    {
      "customerId": 1234,
      "orderDate": "2022-01-01T12:34:56",
      "lineItems": [
        {"item": "ABC","quantity": 12, "totalPrice": 49.25},
        {"item": "XYZ","quantity": 98, "totalPrice": 99.25}
      ]
    }

  order1_update1.json: |
    {"newStatus": "CANCELLED"}
  
  order1_update2.json: |
    {"newStatus": "CANCELLED"}

  order2.json: |
    {
      "customerId": 9876,
      "orderDate": "2023-09-01T00:12:34",
      "lineItems": [
        {"item": "QWE","quantity": 5, "totalPrice": 10.25},
        {"item": "POI","quantity": 3, "totalPrice": 25.25},
        {"item": "STS","quantity": 7, "totalPrice": 5.25}
      ]
    }

  order2_update1.json: |
    {"newStatus": "SHIPPED"}
  
  order2_update2.json: |
    {"newStatus": "SHIPPED"}

  order2_update3.json: |
    {"newStatus": "SHIPPED"}
